### ISSUE TITLE
Panic when initializing `ash::Device`

### ISSUE THREAD

**Issue by swlody** [sebbbi/rust_test#1]
When running in both debug and release modes, I am getting the following error message:

```
thread 'main' panicked at 'attempted to zero-initialize type `ash::Device`, which is invalid', C:\Users\Sam\.rustup\toolchains\nightly-x86_64-pc-windows-msvc\lib/rustlib/src/rust\library\core\src\mem\mod.rs:623:9`
```

When tracing through in the debugger, this seems to originate in a bug in the vk_mem crate's `Default` implementation for `AllocatorCreateInfo` [here](https://github.com/sebbbi/rust_test/blob/main/src/vulkan_base.rs#L354). Calling `AllocatorCreateInfo::Default()` initializes the `ash::Device` struct with `mem::zeroed()` as seen [here](https://docs.rs/vk-mem/0.2.2/src/vk_mem/lib.rs.html#271), which according to the runtime panic message is invalid (although I'm not familiar with the specific Rust rules which prevent this.)

In order to avoid this bug in the vk_mem crate, the `Default::default()` call needs to be avoided here and the default values need to be initialized manually, i.e.:

```rust
let allocator_create_info = vk_mem::AllocatorCreateInfo {
    physical_device: pdevice,
    device: device.clone(),
    instance: instance.clone(),
    flags: vk_mem::AllocatorCreateFlags::NONE,
    preferred_large_heap_block_size: 0,
    frame_in_use_count: 0,
    heap_size_limits: None,
};
```

**Comment by sebbbi** [comment]
Strange. I have never seen this panic. I can try to fix it blindly, but I can't repro it.

**Comment by swlody** [comment]
My bad! Looks like this is new behavior in nightly but shouldn't manifest using stable Rust: https://github.com/rust-lang/rust/issues/77499

The issue has been fixed in vk_mem already: https://github.com/gwihlidal/vk-mem-rs/pull/39
