### ISSUE TITLE
Mismatched Types (2 different versions of ash?)

### ISSUE THREAD

**Issue by Ihaa21** [sebbbi/rust_test#2]
Hey, I tried building this project on a new install of rust and everything but I'm running into a few errors (there are 12 but here are 2 examples):

"error[E0308]: mismatched types
   --> src\vulkan_base.rs:351:34
    |
351 |                 physical_device: pdevice,
    |                                  ^^^^^^^ expected struct `ash::vk::definitions::PhysicalDevice`, found struct `PhysicalDevice`
    |
    = note: perhaps two different versions of crate `ash` are being used?

error[E0308]: mismatched types
   --> src\vulkan_base.rs:352:25
    |
352 |                 device: device.clone(),
    |                         ^^^^^^^^^^^^^^ expected struct `ash::device::Device`, found struct `vulkan_base::ash::Device`
    |
    = note: perhaps two different versions of crate `ash` are being used?"

I tried building on various different versions of rust compiler but either they fail to run or they throw the above errors (1.45.0 - 1.50.0). Do you know what might be wrong/if there is a specific rust version I need to use? This is on a Windows machine.

**Comment by acowley** [comment]
I was able to address this in two ways; you can try either:

- bumping the `ash` and `ash-window` dependencies of this project to `0.32` and `0.6`
- editing `Cargo.lock` to get `vk-mem` to use version `0.31.0` of `ash` 

(The tool `cargo tree` is very useful for diagnosing these things.) That said, while the program builds for me now, all it produces is a black window, so there seems to be some incompatibility remaining!

**Comment by sebbbi** [comment]
Need to test on newest Rust when I have an extended weekend for the next time.

**Comment by sebbbi** [comment]
fixed
